スタート画面からゲーム開始画面への切り替わりを実装した
Shibata0806/frontend_team2019 pull request #12
Opened 2019-12-12 12:20 UTC by samopst

2019-12-12 12:29 UTC, samopst commented
<img width="1439" alt="スクリーンショット 2019-12-12 21 26 00" src="https://user-images.githubusercontent.com/51643156/70712161-82e17d80-1d26-11ea-9a9a-c9154ded6dde.png">
<img width="699" alt="スクリーンショット 2019-12-12 21 26 07" src="https://user-images.githubusercontent.com/51643156/70712168-883ec800-1d26-11ea-8360-40bdc37ca251.png">

2019-12-12 12:41 UTC, shibatamasahito requested changes
コメントしました。

2019-12-12 12:41 UTC, shibatamasahito commented on pages/nakachi_s_kota/typing/typing.html
> +        <h1 v-text="currentWord()"></h1>
js側で`currentWord`をmethodsからdataに変更して、`{{currentWord}}`にして表示するのがよさそうです。

2019-12-12 12:41 UTC, shibatamasahito commented on pages/nakachi_s_kota/typing/script.js
> +        currentWord() {
currentWordはdateに変数として持たせ、returnではなく、
this.currentWord =  unsolvedWords[randomIndex]
としてあげるのがよさそうです。

2019-12-12 12:46 UTC, shibatamasahito commented on pages/nakachi_s_kota/typing/script.js
> +            this.$nextTick(() => {
vuejsだと仮想DOMにアクセスするのがお作法なので、あまりdocument.getElementById系は使わないです。
代わりに、$refsというものを使うのはどうでしょうか？
https://qiita.com/akicho8/items/b4d071ea7eae562f529d

2019-12-12 12:46 UTC, shibatamasahito commented on pages/nakachi_s_kota/typing/script.js
> +                document.getElementById('input-typing').focus()
vuejsだと仮想DOMにアクセスするのがお作法なので、あまりdocument.getElementById系は使わないです。
代わりに、$refsというものを使うのはどうでしょうか？
https://qiita.com/akicho8/items/b4d071ea7eae562f529d

2019-12-12 12:58 UTC, ghost reviewed
確認しました。
変数名で1個だけ指摘しましたが、好みの問題の気もするので、そのままでもいいかなと僕は思います。

ロジックについては特に気になることはありません。

2019-12-12 12:58 UTC, kameda-opst commented on pages/nakachi_s_kota/typing/script.js
> +            this.trying = true;
「現在ゲーム中かどうか」で使っているし、利用しているところもゲーム中の画面を出すかどうかの判定(`if`)で用いてるから、`isTrying`でもいいかなと思った。

2019-12-17 11:40 UTC, samopst commented on pages/nakachi_s_kota/typing/script.js
> +            this.trying = true;
ご指摘ありがとうございます！
修正します。

2019-12-17 11:40 UTC, samopst commented on pages/nakachi_s_kota/typing/script.js
> +                document.getElementById('input-typing').focus()
ご指摘ありがとうございます！
修正します。

2019-12-17 11:40 UTC, samopst commented on pages/nakachi_s_kota/typing/script.js
> +        currentWord() {
ご指摘ありがとうございます！
修正します！

2019-12-17 11:57 UTC, kameda-opst commented on pages/nakachi_s_kota/typing/script.js
> +            this.trying = true;
@samopst 
確認しました。修正ありがとうございます。

2020-01-26 07:09 UTC, merged